# Generated by Django 4.1.3 on 2023-04-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=200)),
                ('lname', models.TextField(max_length=200)),
                ('gender', models.TextField(max_length=200)),
                ('whatsapp', models.IntegerField(max_length=100)),
                ('location', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
