# Generated by Django 4.1.3 on 2023-05-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_mydata_fname_alter_mydata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='whatsapp',
            field=models.IntegerField(),
        ),
    ]
